# DO NOT CHANGE unless you know how to manually upgrade the configuration file
version: 1

# Available: "en_US", "zh_CN"
language: "en_US"

# Available: "linear", "logarithmic"
algorithm: "logarithmic"

# Damage greater than this will it be limited
threshold: 30.0

# Controls the magnitude of damage limitation.
# For "linear" algorithm:
#  - The factor must be between 0.0 (fully limited to the threshold) and 1.0 (no limitation applied)
#  - The smaller the value, the stronger the limitation
# For "logarithmic" algorithm:
#  - The factor must be greater than 1.0
#  - The larger the value, the stronger the limitation
factor: 1.5

# Whether to alert console that someone has caused damage greater than threshold
# true=Yes, false=No
notifyConsole: true
